#!/usr/bin/env node
'use strict';
// GBD Codex CLI adapter — emits Codex custom prompts + an AGENTS.md from the manifest.
//
// Codex CLI custom prompts are Markdown files in ~/.codex/prompts/<name>.md, invoked as
// /<name>. They support argument interpolation: $ARGUMENTS (all args), $1..$9 (positional).
// Project-level persistent guidance lives in AGENTS.md at the repo root.
//
// We emit:
//   <target>/prompts/gbd-<name>.md   one Codex custom prompt per GBD skill (invoke /gbd-<name>)
//   <target>/AGENTS.md               persistent GBD operating guide (conventions + degradation)
//   <target>/core/                   the portable GBD core (workflows, references, templates)
//
// Default output: adapters/codex/dist/.  Use --target ~/.codex to install prompts directly
// (note: AGENTS.md belongs at your book project root, not in ~/.codex).
//
// Generated output is NOT yet battle-tested — see README.md.  Node built-ins only.

const fs = require('fs');
const path = require('path');
const {
  REPO_ROOT, loadManifest, readBody, rewriteBody, ensureDir, copyDir,
} = require('../lib/manifest.cjs');

const CORE_ROOT = '~/.gbd/core';

function parseArgs(argv) {
  const args = { target: path.join(__dirname, 'dist') };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--target') args.target = argv[++i];
    else if (argv[i].startsWith('--target=')) args.target = argv[i].slice('--target='.length);
  }
  return args;
}

function degradationNote(skill, manifest) {
  const notes = [];
  if (skill.capabilities.includes('spawn-agent')) {
    const agents = skill.spawns.map((n) => {
      const a = manifest.agents.find((x) => x.name === n);
      return a ? `- **${a.name}** — ${a.summary}` : `- ${n}`;
    });
    notes.push(
      '**Subagents:** This workflow was written for Claude Code, which spawns dedicated ' +
      'subagents. Codex runs as a single agent, so perform each spawned agent\'s job ' +
      'yourself as sequential steps in this session, in spawn order, treating each agent\'s ' +
      'completion marker as a checkpoint. Agents this workflow relies on:\n' + agents.join('\n')
    );
  }
  if (skill.capabilities.includes('ask-user')) {
    notes.push(
      '**Structured questions:** Where the workflow uses an AskUserQuestion gate, ask in ' +
      'plain language and wait for the answer before proceeding past a hard gate.'
    );
  }
  notes.push(
    '**Includes:** `' + CORE_ROOT + '/...` references point at the GBD core on disk. Read ' +
    'those workflow/reference/template files before acting.'
  );
  return notes.join('\n\n');
}

function buildPrompt(skill, manifest) {
  const { body } = readBody(skill.body);
  const rewritten = rewriteBody(body, { coreRoot: CORE_ROOT, argsToken: '$ARGUMENTS' });
  return [
    '# ' + skill.command + ' — ' + skill.summary,
    '',
    '> **GBD on Codex (adapter notes).**',
    '>',
    degradationNote(skill, manifest).split('\n').map((l) => '> ' + l).join('\n'),
    '',
    'Arguments: $ARGUMENTS',
    '',
    rewritten.trim(),
    '',
  ].join('\n');
}

function buildAgentsMd(manifest) {
  const rows = manifest.skills
    .map((s) => `| \`${s.command}\` | ${s.lifecycle_group} | ${s.summary} |`)
    .join('\n');
  return [
    '# AGENTS.md — Get Books Done (GBD)',
    '',
    '> Generated by `adapters/codex/build.cjs`. Place this at the root of a book project so',
    '> Codex picks up GBD operating rules. Custom prompts (`/gbd-*`) live in `~/.codex/prompts/`.',
    '',
    '## What GBD is',
    '',
    'GBD is a structured book-writing framework: gather context → outline → discuss → plan →',
    'draft → verify against the promise to the reader → review → ship. Planning artifacts live',
    'in `.book/`; prose lives in `manuscript/`. The portable core (workflows, references,',
    'templates) is installed at `' + CORE_ROOT + '`.',
    '',
    '## Operating rules on Codex',
    '',
    '- Codex is a **single agent**. Where a GBD workflow spawns subagents (planner, drafter,',
    '  verifier, editor, …), perform their jobs yourself as sequential steps, honoring each',
    "  agent's completion marker (e.g. `## PLANNING COMPLETE`, `## Verification Complete`).",
    '- At hard gates, ask the user in plain language and **wait** for confirmation.',
    '- One atomic commit per scene drafted / edit applied (see',
    '  `' + CORE_ROOT + '/references/git-conventions.md`).',
    '- Read the relevant workflow under `' + CORE_ROOT + '/workflows/` before acting.',
    '',
    '## Commands',
    '',
    '| Command | Stage | Does |',
    '|---|---|---|',
    rows,
    '',
    '## Agents (run their bodies inline as steps)',
    '',
    manifest.agents.map((a) =>
      `- **${a.name}** — ${a.summary}` +
      (a.completion_marker ? ` _(marker: \`${a.completion_marker}\`)_` : '')
    ).join('\n'),
    '',
  ].join('\n');
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const manifest = loadManifest();
  const target = path.resolve(args.target);

  const promptsDir = path.join(target, 'prompts');
  ensureDir(promptsDir);

  let count = 0;
  for (const skill of manifest.skills) {
    fs.writeFileSync(path.join(promptsDir, skill.name + '.md'), buildPrompt(skill, manifest));
    count++;
  }

  fs.writeFileSync(path.join(target, 'AGENTS.md'), buildAgentsMd(manifest));

  const coreDest = path.join(target, 'core');
  copyDir(path.join(REPO_ROOT, 'core'), coreDest);

  console.log('[codex] target: ' + target);
  console.log('[codex] prompts: ' + count + ' -> ' + promptsDir + '/gbd-*.md');
  console.log('[codex] AGENTS.md -> ' + path.join(target, 'AGENTS.md'));
  console.log('[codex] core: copied -> ' + coreDest + ' (install to ' + CORE_ROOT + ')');
}

main();
