#!/usr/bin/env node
'use strict';
// GBD Gemini CLI adapter — emits Gemini CLI custom commands from the manifest + bodies.
//
// Gemini CLI custom commands are TOML files discovered under <root>/commands/*.toml
// (project: ./.gemini/commands, user: ~/.gemini/commands). Each file has:
//     description = "..."   # shown in the command picker
//     prompt      = """..."""# the prompt injected when the command runs
// Subdirectories namespace commands with ':'. We keep flat files named gbd-<name>.toml
// so the command stays /gbd-<name> (hyphen form), matching GBD conventions.
//
// {{args}} in a prompt is replaced by Gemini with the user's argument string.
//
// Default output: adapters/gemini-cli/dist/  (a ready-to-copy .gemini tree + core).
// Use --target <dir> to emit into a Gemini config dir (e.g. ~/.gemini).
//
// Generated output is NOT yet battle-tested — see README.md.
//
// Node built-ins only.

const fs = require('fs');
const path = require('path');
const {
  REPO_ROOT, loadManifest, readBody, rewriteBody, extractBlock, CAP_DESC,
  ensureDir, copyDir,
} = require('../lib/manifest.cjs');

const CORE_ROOT = '~/.gbd/core';

function parseArgs(argv) {
  const args = { target: path.join(__dirname, 'dist') };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--target') args.target = argv[++i];
    else if (argv[i].startsWith('--target=')) args.target = argv[i].slice('--target='.length);
  }
  return args;
}

function tomlString(s) {
  // TOML basic string: escape backslash, quote, control chars.
  return '"' + String(s)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\t/g, '\\t') + '"';
}

function tomlMultiline(s) {
  // TOML multi-line basic string. Escape backslashes and any """ sequence.
  const body = String(s).replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"');
  return '"""\n' + body + '\n"""';
}

// Build the degradation preamble injected into every command prompt, tailored to caps.
function degradationNote(skill, manifest) {
  const notes = [];
  if (skill.capabilities.includes('spawn-agent')) {
    const agents = skill.spawns.map((n) => {
      const a = manifest.agents.find((x) => x.name === n);
      return a ? `- ${a.name}: ${a.summary}` : `- ${n}`;
    });
    notes.push(
      'SUBAGENTS: This workflow was authored for Claude Code, which spawns dedicated ' +
      'subagents. Gemini CLI has no native subagent mechanism, so perform each spawned ' +
      "agent's job yourself as a sequential step in this same session, in the order the " +
      'workflow spawns them, honoring each agent\'s completion marker as your own checkpoint. ' +
      'The agents this workflow relies on (run their prompt bodies in order):\n' +
      agents.join('\n')
    );
  }
  if (skill.capabilities.includes('ask-user')) {
    notes.push(
      'ASK-USER: Where the workflow uses a structured AskUserQuestion gate, ask the ' +
      'question in plain chat and WAIT for the answer before proceeding. Do not assume an ' +
      'answer at a hard gate.'
    );
  }
  notes.push(
    'INCLUDES: References like ' + CORE_ROOT + '/workflows/<file> point at the GBD core ' +
    'installed on disk. Read those files (workflows/, references/, templates/) before acting; ' +
    'they are not auto-inlined here.'
  );
  return notes.join('\n\n');
}

function buildPrompt(skill, manifest) {
  const { body } = readBody(skill.body);
  const rewritten = rewriteBody(body, { coreRoot: CORE_ROOT, argsToken: '{{args}}' });
  const note = degradationNote(skill, manifest);
  return [
    '# ' + skill.command + ' (' + skill.name + ')',
    '',
    '<<GEMINI_ADAPTER_NOTES>>',
    note,
    '<<END_ADAPTER_NOTES>>',
    '',
    'Arguments: {{args}}',
    '',
    rewritten.trim(),
  ].join('\n');
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const manifest = loadManifest();
  const target = path.resolve(args.target);

  const cmdDir = path.join(target, 'commands');
  ensureDir(cmdDir);

  let count = 0;
  for (const skill of manifest.skills) {
    const desc = skill.summary;
    const prompt = buildPrompt(skill, manifest);
    const toml = [
      '# Generated by adapters/gemini-cli/build.cjs — do not edit by hand.',
      '# Source of truth: commands/manifest.json + ' + skill.body,
      'description = ' + tomlString(desc),
      'prompt = ' + tomlMultiline(prompt),
      '',
    ].join('\n');
    fs.writeFileSync(path.join(cmdDir, skill.name + '.toml'), toml);
    count++;
  }

  // Ship the portable core alongside so the path references resolve once copied to ~/.gbd/core.
  const coreDest = path.join(target, 'core');
  copyDir(path.join(REPO_ROOT, 'core'), coreDest);

  console.log('[gemini-cli] target: ' + target);
  console.log('[gemini-cli] commands: ' + count + ' -> ' + cmdDir + '/gbd-*.toml');
  console.log('[gemini-cli] core: copied -> ' + coreDest + ' (install to ' + CORE_ROOT + ')');
}

main();
